# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VoltPop
logo: /assets/images/vp_logo_clear-88x88.png
email: dfoulks@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
#Carpe Fulgur
#  VoltPopulous Consulting was founded to help empower small businesses and local
#  organizations build an infrastructure that suits their needs as well as the needs of 
#  their users. We strive to support both our customers and Open Source communities by
#  leveraging our knowledge and experience in Open Source solutions.
  #baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: VoltPop
github_username:  dfoulks

# Build settings
repository: "warwalrux/voltpopulous-site"
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: air
plugins:
  - jekyll-include-cache
  #- jekyll-feed

collections:
  blogs:
    output: true
    permalink: /:collection/:path/
#  lore:
#    output: true
#    permalink: /:collection/:path/

include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
